export default interface UserData {
  id: number;
  name: string;
  business_name: string | null;
  business_type: string | null;
  location: string | null;
  address_city: string | null;
  address_zip: string | null;
  address_state: string | null;
  description: string | null;
  business_document: string | null;
  currency: string | null;
  timezone: string | null;
  profile: string;
  admin_id: number;
  brand: string | null;
  email: string;
  business_email: string | null;
  email_verified_at: string | null;
  phone: string;
  business_phone: string | null;
  dob: string | null;
  commission: string;
  job_title: string;
  joining_date: string;  end_date: string | null;
  role: string;
  address: string;
  salary: string;
  work_time_to: string;
  is_active: number;
  work_time_from: string;
  plan_id: number;
  remember_token: string | null;
  created_at: string;
  updated_at: string;
  member_ships_id: number | null;
  gst_active: number;
  gst_percentage: string | null;
  gst_number: string | null;
  lat: number | null;
  lon: number | null;
  image: string;
  identity_proof: string;
  opening_hours: string;
  day_off: string;
  phone_verified: number;
}

